// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'product.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Product _$ProductFromJson(Map<String, dynamic> json) => Product(
  id: json['id'],
  name: json['name'] as String?,
  price: parseJsonDouble(json['price']),
  quantity: parseJsonInt(json['quantity']),
  description: json['description'] as String?,
  barcode: json['barcode'] as String?,
  categoryId: parseJsonInt(json['category_id']),
  currency: json['currency'] as String?,
  imageUrl: json['image_url'] as String?,
  images: (json['images'] as List<dynamic>?)?.map((e) => e as String).toList(),
  localImages: (json['local_images'] as List<dynamic>?)
      ?.map((e) => e as String)
      .toList(),
  isOnline: json['is_online'] as bool?,
  wentOnlineAt: json['went_online_at'] as String?,
  viewCount: parseJsonInt(json['view_count']),
  rating: parseJsonDouble(json['rating']),
  reviewCount: parseJsonInt(json['review_count']),
  shopName: json['shop_name'] as String?,
  storeId: parseJsonInt(readStoreId(json, 'store_id')),
  lat: parseJsonDouble(json['lat']),
  lng: parseJsonDouble(json['lng']),
  city: json['city'] as String?,
  cityId: json['city_id'] as String?,
  village: json['village'] as String?,
  villageId: json['village_id'] as String?,
  country: json['country'] as String?,
  countryCode: json['country_code'] as String?,
  storeCity: json['store_city'] as String?,
  storeVillage: json['store_village'] as String?,
  storeCountry: json['store_country'] as String?,
  displayPrice: parseJsonDouble(json['display_price']),
  displayCurrency: json['display_currency'] as String?,
  lowStockThreshold: parseJsonInt(json['low_stock_threshold']),
  createdAt: json['created_at'] as String?,
  updatedAt: json['updated_at'] as String?,
  imagePath: json['image_path'] as String?,
  pendingCreate: json['_pendingCreate'] as bool?,
  pendingUpdate: json['_pendingUpdate'] as bool?,
  pendingApproval: json['pending_approval'] as bool?,
  listOnline: json['list_online'] as bool?,
);

Map<String, dynamic> _$ProductToJson(Product instance) => <String, dynamic>{
  'id': ?instance.id,
  'name': ?instance.name,
  'price': ?instance.price,
  'quantity': ?instance.quantity,
  'description': ?instance.description,
  'barcode': ?instance.barcode,
  'category_id': ?instance.categoryId,
  'currency': ?instance.currency,
  'image_url': ?instance.imageUrl,
  'images': ?instance.images,
  'local_images': ?instance.localImages,
  'is_online': ?instance.isOnline,
  'went_online_at': ?instance.wentOnlineAt,
  'view_count': ?instance.viewCount,
  'rating': ?instance.rating,
  'review_count': ?instance.reviewCount,
  'shop_name': ?instance.shopName,
  'store_id': ?instance.storeId,
  'lat': ?instance.lat,
  'lng': ?instance.lng,
  'city': ?instance.city,
  'city_id': ?instance.cityId,
  'village': ?instance.village,
  'village_id': ?instance.villageId,
  'country': ?instance.country,
  'country_code': ?instance.countryCode,
  'store_city': ?instance.storeCity,
  'store_village': ?instance.storeVillage,
  'store_country': ?instance.storeCountry,
  'display_price': ?instance.displayPrice,
  'display_currency': ?instance.displayCurrency,
  'low_stock_threshold': ?instance.lowStockThreshold,
  'created_at': ?instance.createdAt,
  'updated_at': ?instance.updatedAt,
  'image_path': ?instance.imagePath,
  '_pendingCreate': ?instance.pendingCreate,
  '_pendingUpdate': ?instance.pendingUpdate,
  'pending_approval': ?instance.pendingApproval,
  'list_online': ?instance.listOnline,
};
